services:
  frontend:
    build:
      context: ./Sources/client
    container_name: gardeReady-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Sources/client:/app
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./Sources/api
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./Sources/api:/app
    environment:
      APP_ENV: dev

  database:
    image: postgres:latest
    container_name: gardeReady-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gardeready
    ports:
      - "5432:5432"
    volumes:
      # - ./database/db_data:/var/lib/postgresql/data
      - ./Sources/database/initdb:/docker-entrypoint-initdb.d/

volumes:
  db_data:
